### ISSUE TITLE
Installation of v2.0.7 errors.

### ISSUE THREAD

**Issue by ringods** [kiegroup/act-js#33]
**Describe the bug**
Installation of `@kie/act-js` v2.0.7 fails with this error:

```
npm install --save-dev @kie/act-js  
npm ERR! code 127
npm ERR! path /Users/ringods/Projects/pulumi/build-automation/node_modules/@kie/act-js
npm ERR! command failed
npm ERR! command sh -c npm run prebuild
npm ERR! > @kie/act-js@2.0.7 prebuild
npm ERR! > ./scripts/act.sh 0.2.43
npm ERR! sh: ./scripts/act.sh: No such file or directory

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ringods/.npm/_logs/2023-04-25T14_57_58_799Z-debug-0.log
```

**To Reproduce**

```sh
$ npm install --save-dev @kie/act-js
```

**Expected behavior**

Installation should work as with earlier versions. As a workaround, I fixed my version to v2.0.6.

**Logs**

Snippet from the generated log file:

```
83 info run @kie/act-js@2.0.7 preinstall { code: 127, signal: null }
84 timing reify:rollback:createSparse Completed in 33ms
85 timing reify:rollback:retireShallow Completed in 0ms
86 timing command:install Completed in 787ms
87 verbose stack Error: command failed
87 verbose stack     at ChildProcess.<anonymous> (/Users/ringods/.volta/tools/image/node/16.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
87 verbose stack     at ChildProcess.emit (node:events:527:28)
87 verbose stack     at maybeClose (node:internal/child_process:1092:16)
87 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
88 verbose pkgid @kie/act-js@2.0.7
```

**Additional context**

There is a [v2.0.7](https://www.npmjs.com/package/@kie/act-js/v/2.0.7) on npmjs.com but not a corresponding [Github tag](https://github.com/kiegroup/act-js/tags), nor [Github release](https://github.com/kiegroup/act-js/releases).

**Comment by shubhbapna** [comment]
Might be fixed in #31 when I completely remove the bash script and rely on a post install hook to run a nodejs script 

Released v2.0.7 tag. Sorry about that

**Comment by shubhbapna** [comment]
@ringods please try to install 2.0.8 and let me know if that works for you

**Comment by ringods** [comment]
@shubhbapna The install of v2.0.8 seems to work and it now fetches the right binary for `act` when running on my Apple M1 machine:

```
$ file node_modules/@kie/act-js/build/bin/act 
node_modules/@kie/act-js/build/bin/act: Mach-O 64-bit executable arm64
```
