### ISSUE TITLE
Passing `undefined` as `cwd` to constructor causes strange behavior

### ISSUE THREAD

**Issue by JoshMcCullough** [kiegroup/act-js#45]
**Describe the bug**
` new Act(gh.repo.getPath("some invalid repo"))` ends up passing `undefined` to the `Act` constructor. This, in my case, caused an error where (somehow) a `.travis.yml` file was being parsed by Act, with the following output:

> Error: workflow is not valid. .travis.yml: yaml: unmarshal errors:
>   line 28: cannot unmarshal !!seq into map[string]string

In this case, the `.travis.yml` file was located in a Node module at path: `/path/to/my/project/node_modules/function-bind`

**To Reproduce**
Pass `undefined` to the constructore while you have an invalid `*.yml` file somewhere e.g. under `node_modules`.

**Expected behavior**
The constructor probably should require a `cwd`, or throw if one is provided as `null` or `undefined`.

**Comment by JoshMcCullough** [comment]
And if the answer is "yes, it is valid to provide a null/undefinfed path in the constructor", maybe that rules should be changed to require a path even if it's just `./`.

**Comment by shubhbapna** [comment]
> And if the answer is "yes, it is valid to provide a null/undefinfed path in the constructor", maybe that rules should be changed to require a path even if it's just ./.

So when we provide null/undefined path in the constructor then it implicitly means the current working directory - https://github.com/kiegroup/act-js/blob/main/src/act/act.ts#L29

However it seems that when you do it from the root of the directory which contains a node_module directory, `act` will go through and try to recursively detect workflow files.

**Comment by shubhbapna** [comment]
Yes lets stick with convention that if no path is passed in the constructor then the current working directory will be used. I will update the readme.

Although it is annoying that `act` tries to recurse through node_modules. I will see if `--no-recurse` flag has any side effects.
