### ISSUE TITLE
"do not mock" test fails in interactive console

### ISSUE THREAD

**Issue by TWiStErRob** [kiegroup/act-js#61]
**To Reproduce**
1. Clone this repo
2. `npm test` or `npx jest`

**Expected behavior**
Pass

**Logs**
<img width="533" alt="image" src="https://github.com/kiegroup/act-js/assets/2906988/2078e715-59a7-4e9a-95dc-8e924e6d4b0b">

**Additional context**
Notice that the expected 200 is yellow. That's part of the string somehow!

**Comment by shubhbapna** [comment]
Interestingly, I am not able to reproduce it. Could you share some more details about the environment you were running this in? Maybe the OS and the node version?

**Comment by TWiStErRob** [comment]
I'm away from work, but AFAIR:
Node 20.10.0
MacOS is latest as far as M1 Pro gets updated I guess it was macOS Sonoma | 14.1.2
and ZSH.

**Comment by shubhbapna** [comment]
I am not able to test it on a mac but at least when I am using node 20 I am not seeing this issue. Once you are back, can you test it again and see if this is still showing up?

**Comment by TWiStErRob** [comment]
Exact same problem on Windows 10 with Node 18, and `cmd` shell:
![image](https://github.com/kiegroup/act-js/assets/2906988/f207f737-a54f-40a4-9749-a520fb9931c3)

Do you have colors in your output?

**Comment by shubhbapna** [comment]
I do have colors in my output

**Comment by shubhbapna** [comment]
Oh I was able to reproduce it now. Not sure what changed though
